### ISSUE TITLE
Twitter Scraper returns empty dataframe

### ISSUE THREAD

**Issue by kartzke** [mldsveda/PyScrappy#15]
Hi, this is a great project!  I tried using the twitter scraper with the following code and I get an empty dataframe returned.  I don't see any errors or exceptions, not sure how to troubleshoot this.  Any ideas?

```
import PyScrappy as ps

obj = ps.SocialMediaScrapper()
df = obj.twitter_scrapper('#thailand', 1)
df.head()
```

Full text output looks like this: 

```
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 92.0.4515
[WDM] - Get LATEST driver version for 92.0.4515
[WDM] - Driver [/Users/ryan/.wdm/drivers/chromedriver/mac64/92.0.4515.107/chromedriver] found in cache
```

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/713503/128299232-8f5123f7-e431-49a2-808a-bb9c55180a80.png">

**Comment by vedaant2000** [comment]
Hey @kartzke, thanks for using this package and raising an issue. Actually, it would really be helpful if you could mention the IDE in which you implemented this block of code, as we implemented the same chunk of code on both Jupyter notebooks as well as Jupyter lab, but didn't find any issue of an empty data frame as such. Below we are attaching the screenshot as well.
![Jupyter Lab](https://user-images.githubusercontent.com/76814037/128305152-013cb13f-a713-401e-9f30-f83cfccac5df.jpeg)
![Notebook](https://user-images.githubusercontent.com/76814037/128305158-921c0c5d-582f-4ff8-8160-d43470e76935.jpeg)

**Comment by kartzke** [comment]
Hi @vedaant2000, I'm using VS Code on an Apple M1 MacBook.  Python 3.9

**Comment by kartzke** [comment]
I just gave this another try with a regular Jupyter Notebook, same result.  

<details>
<summary>conda list</summary>

conda list
packages in environment at /Users/ryan/miniforge3/envs/findash:

Name                    Version                   Build  Channel
aiohttp                   3.7.4.post0              pypi_0    pypi
appnope                   0.1.2            py39h2804cbe_1    conda-forge
argon2-cffi               20.1.0           py39h5161555_2    conda-forge
async-timeout             3.0.1                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.9.3                    pypi_0    pypi
bleach                    4.0.0              pyhd8ed1ab_0    conda-forge
ca-certificates           2021.5.30            h4653dfc_0    conda-forge
certifi                   2021.5.30        py39h2804cbe_0    conda-forge
cffi                      1.14.6           py39hda8b47f_0    conda-forge
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
configparser              5.0.2                    pypi_0    pypi
crayons                   0.4.0                    pypi_0    pypi
dateparser                1.0.0                    pypi_0    pypi
debugpy                   1.4.1            py39hfb83b0d_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
idna                      3.2                      pypi_0    pypi
importlib-metadata        4.6.3            py39h2804cbe_0    conda-forge
ipykernel                 6.0.3            py39h32adebf_0    conda-forge
ipython                   7.26.0           py39h32adebf_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py39h2804cbe_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39h2804cbe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
libcxx                    12.0.1               h168391b_0    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
markupsafe                2.0.1            py39h5161555_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mistune                   0.8.4           py39h5161555_1004    conda-forge
multidict                 5.1.0                    pypi_0    pypi
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py39h2804cbe_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
notebook                  6.4.1              pyha770c72_0    conda-forge
numpy                     1.21.1                   pypi_0    pypi
openssl                   1.1.1k               h27ca646_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.1                    pypi_0    pypi
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       21.1.3             pyhd8ed1ab_0    conda-forge
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py39h5161555_2    conda-forge
pyscrappy                 0.0.9                    pypi_0    pypi
python                    3.9.6           h54d631c_1_cpython    conda-forge
python-binance            1.0.12                   pypi_0    pypi
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1                   pypi_0    pypi
pyzmq                     22.1.0           py39h02c6a76_0    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
regex                     2021.7.6                 pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.7.1              pyhd8ed1ab_0    conda-forge
setuptools                49.6.0           py39h2804cbe_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.2.1                    pypi_0    pypi
sqlite                    3.36.0               h72a2b83_0    conda-forge
terminado                 0.10.1           py39h2804cbe_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
tornado                   6.1              py39h5161555_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing-extensions         3.10.0.0                 pypi_0    pypi
tzdata                    2021a                he74cb21_1    conda-forge
tzlocal                   2.1                      pypi_0    pypi
ujson                     4.0.2                    pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webdriver-manager         3.4.2                    pypi_0    pypi
webencodings              0.5.1                      py_1    conda-forge
websockets                9.1                      pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yarl                      1.6.3                    pypi_0    pypi
zeromq                    4.3.4                h9f76cd9_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge

</details>


<img width="1247" alt="image" src="https://user-images.githubusercontent.com/713503/128458432-b3ea7c05-4735-48ee-a5bb-ae579dcd602a.png">
